onboarding = false
[keys]
prefix = "ctrl+a"
focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"

split_horizontal = "prefix+s"
split_vertical = "prefix+v"

previous_tab = "prefix+p"
next_tab = "prefix+n"

previous_workspace = "prefix+ctrl+s"
next_workspace = "prefix+ctrl+d"
workspace_picker = "prefix+w"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
open_notification_target = ""

reload_config = "prefix+r"

[[keys.command]]
key = "prefix+f"
type = "popup"
command = "~/.local/scripts/herdr-s"
width = "80%"
height = "80%"

[theme]
name = "terminal"

# Match One Dark in Neovim and Ghostty
[theme.custom]
panel_bg = "#282c34"
accent = "#61afef"
surface0 = "#353b45"
surface1 = "#3e4451"
surface_dim = "#21252b"
overlay0 = "#737c8c"
overlay1 = "#9da5b4"
text = "#abb2bf"
subtext0 = "#9da5b4"
mauve = "#c678dd"
green = "#98c379"
yellow = "#e5c07b"
red = "#e06c75"
blue = "#61afef"
teal = "#56b6c2"
peach = "#d19a66"

[ui]
agent_panel_sort = "spaces"
prompt_new_tab_name = false
hide_tab_bar_when_single_tab = true
pane_scrollbars = false
sidebar_collapsed_mode = "hidden"

[experimental]
kitty_graphics = true

